### ISSUE TITLE
problem bootstrapping cm3 from github images current as of today

### ISSUE THREAD

**Issue by mikanystrom-intel** [modula3/cm3#1018]
Tried to email m3devel but maybe the list is dead now?

Hi m3devel,

I am trying to follow the directions at 

https://github.com/modula3/cm3/wiki/Getting-Started

that went OK

and then build the distribution through cloning the cm3 repo and

cd scripts/python
./make-dist.py

It all looks pretty good till I get through the build, and then this happens:

no packages left
mkdir -p /tmp/tmp1odesum8/cm3-min-AMD64_LINUX-d5.11.9-Linux4.12.14-20220330/license
cp -Pv /nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3/COPYRIGHT-BSD /tmp/tmp1odesum8/cm3-min-AMD64_LINUX-d5.11.9-Linux4.12.14-20220330/license/COPYRIGHT-BSD
cp -Pv /nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3/COPYRIGHT-CMASS /tmp/tmp1odesum8/cm3-min-AMD64_LINUX-d5.11.9-Linux4.12.14-20220330/license/COPYRIGHT-CMASS
cp -Pv /nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3/COPYRIGHT-COLUMBIA /tmp/tmp1odesum8/cm3-min-AMD64_LINUX-d5.11.9-Linux4.12.14-20220330/license/COPYRIGHT-COLUMBIA
cp -Pv /nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3/COPYRIGHT-DEC /tmp/tmp1odesum8/cm3-min-AMD64_LINUX-d5.11.9-Linux4.12.14-20220330/license/COPYRIGHT-DEC
cp -Pv /nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3/COPYRIGHT-INTEL /tmp/tmp1odesum8/cm3-min-AMD64_LINUX-d5.11.9-Linux4.12.14-20220330/license/COPYRIGHT-INTEL
cp -Pv /nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3/COPYRIGHT-JDP /tmp/tmp1odesum8/cm3-min-AMD64_LINUX-d5.11.9-Linux4.12.14-20220330/license/COPYRIGHT-JDP
cp -Pv /nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3/COPYRIGHT-PURDUE /tmp/tmp1odesum8/cm3-min-AMD64_LINUX-d5.11.9-Linux4.12.14-20220330/license/COPYRIGHT-PURDUE
cp -Pv /nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3/COPYRIGHT-XEROX /tmp/tmp1odesum8/cm3-min-AMD64_LINUX-d5.11.9-Linux4.12.14-20220330/license/COPYRIGHT-XEROX
cp -Pv /nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3/COPYRIGHTS /tmp/tmp1odesum8/cm3-min-AMD64_LINUX-d5.11.9-Linux4.12.14-20220330/license/COPYRIGHTS
cp -Pv /nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3/m3-libs/arithmetic/copyrite.txt /tmp/tmp1odesum8/cm3-min-AMD64_LINUX-d5.11.9-Linux4.12.14-20220330/license/COPYRIGHT-M3NA
cp -Pv /nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3/m3-tools/cvsup/License /tmp/tmp1odesum8/cm3-min-AMD64_LINUX-d5.11.9-Linux4.12.14-20220330/license/COPYRIGHT-JDP-CVSUP
cp -Pv /nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3/m3-sys/COPYRIGHT-CMASS /tmp/tmp1odesum8/cm3-min-AMD64_LINUX-d5.11.9-Linux4.12.14-20220330/license/COPYRIGHT-CMASS
Traceback (most recent call last):
  File "./make-dist.py", line 326, in <module>
    MakeArchives()
  File "./make-dist.py", line 124, in MakeArchives
    TarGzip(PackageSetName)
  File "./make-dist.py", line 114, in TarGzip
    MakeArchive(PackageSetName, "tar cfvz", "tar.gz")
  File "./make-dist.py", line 65, in MakeArchive
    InstallLicense(Root, InstallRoot)
  File "/nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3/scripts/python/pylib.py", line 1952, in InstallLicense
    os.path.walk(os.path.join(Root, "caltech-parser"), Callback, state)
AttributeError: module 'posixpath' has no attribute 'walk'

scfb432501> python --version
Python 3.6.3
scfb432501> cm3 -version
Critical Mass Modula-3 version d5.11.9
  GitInfo: https://github.com/modula3/cm3.git/commit/f952a4931abb9b9f504d97f331bb0dc36e579e66
           https://github.com/modula3/cm3.git/commits/master
           remote: https://github.com/modula3/cm3.git
           revision: f952a4931abb9b9f504d97f331bb0dc36e579e66
           branch: master
  last updated: 2022-02-05
  compiled: 2022-03-30 15:51:34
  configuration: /nfs/site/disks/tfc_fe_zsc7_01/mnystroe/cm3-build-2022-03-30/cm3-dist-2022-03-30/bin/cm3.cfg
  host: AMD64_LINUX
  target: AMD64_LINUX

What's going on here?  I would suspect a python version issue?  Or?

     Mika

**Comment by jaykrell** [comment]
Yeah the python2 to 3 changes really broke all my code. Very disappointing. Can you try python2? Sorry.
You don't need make-dist.py to bootstrap though.

**Comment by jaykrell** [comment]
I continue to think good and bad about Python.

It is an ok language, cross platform, fast enough for many tasks, but the compatibility is not great.

The cross platform-ness has also sort of sort of suffered, i.e. to very old systems..where granted there isn't really anything else..even modern Bash does not run easily on very old systems. Writing code that works with old and new Python isn't easy either. We struggled with Portable sh and BSD and Solaris in the past.

Perhaps we should write tiny C programs and tiny/portable Makefiles. Perhaps.

**Comment by VictorMiasnikov** [comment]
Alternative of Python ( and "Python scripts" ) -- It is good idea

} old and new Python

On OS DOS we have only Python 2.04

> I continue to think good and bad about Python.
> 
> It is an ok language, cross platform, fast enough for many tasks, but the compatibility is not great.
> 
> The cross platform-ness has also sort of sort of suffered, i.e. to very old systems..where granted there isn't really anything else..even modern Bash does not run easily on very old systems. Writing code that works with old and new Python isn't easy either. We struggled with Portable sh and BSD and Solaris in the past.
> 
> Perhaps we should write tiny C programs and tiny/portable Makefiles. Perhaps.

**Comment by VictorMiasnikov** [comment]
( Todo)

**Comment by VictorMiasnikov** [comment]
(Todo)

**Comment by VictorMiasnikov** [comment]
> 

I have some "tactic questions":
 -- commit is principal?
 -- .py scripts  is principal?

**Comment by VictorMiasnikov** [comment]
> 

I have some "tactic questions":
 -- commit is principal?
 -- .py scripts  is principal?

**Comment by VictorMiasnikov** [comment]
( ToDo)

**Comment by VictorMiasnikov** [comment]
( ToDo)

**Comment by 3oheicrw** [comment]
@VictorMiasnikov Excuse me please but what is Phyton? Is it your own Python fork?

**Comment by VictorMiasnikov** [comment]
There's not Python fork in any case. Looks like my smartphone auto-edits Ph  to Phyton -)Python is "true name"23.07.2022, 04:48, "3oheicrw" ***@***.***>:
@VictorMiasnikov Excuse me please but what is Phyton? Is it your own Python fork?
